bundles/catalog-sku-filter/LICENSE, bundles/catalog-sku-filter/codeception.yml, bundles/catalog-sku-filter/composer.json, bundles/catalog-sku-filter/src/FondOfOryx/Client/CatalogSkuFilter/Plugin/SearchExtension/ConcreteSkuQueryExpanderPlugin.php, bundles/catalog-sku-filter/src/FondOfOryx/Client/CatalogSkuFilter/Plugin/SearchExtension/SkuQueryExpanderPlugin.php, bundles/catalog-sku-filter/src/FondOfOryx/Shared/CatalogSkuFilter/CatalogSkuFilterConstants.php, bundles/catalog-sku-filter/src/FondOfOryx/Shared/CatalogSkuFilter/Schema/page.json, bundles/catalog-sku-filter/src/FondOfOryx/Shared/CatalogSkuFilter/Transfer/catalog_sku_filter.transfer.xml, bundles/catalog-sku-filter/src/FondOfOryx/Zed/CatalogSkuFilter/Communication/Plugin/ProductPageSearchExtension/ConcreteSkusProductAbstractMapExpanderPlugin.php, bundles/catalog-sku-filter/src/FondOfOryx/Zed/CatalogSkuFilter/Communication/Plugin/ProductPageSearchExtension/SkuProductAbstractMapExpanderPlugin.php, bundles/catalog-sku-filter/tests/FondOfOryx/Client/CatalogSkuFilter/Plugin/SearchExtension/ConcreteSkuQueryExpanderPluginTest.php, bundles/catalog-sku-filter/tests/FondOfOryx/Client/CatalogSkuFilter/Plugin/SearchExtension/SkuQueryExpanderPluginTest.php, bundles/catalog-sku-filter/tests/FondOfOryx/Zed/CatalogSkuFilter/Communication/Plugin/ProductPageSearchExtension/ConcreteSkusProductAbstractMapExpanderPluginTest.php, bundles/catalog-sku-filter/tests/FondOfOryx/Zed/CatalogSkuFilter/Communication/Plugin/ProductPageSearchExtension/SkuProductAbstractMapExpanderPluginTest.php, bundles/catalog-sku-filter/tests/_bootstrap.php, bundles/catalog-sku-filter/tests/_output/.gitignore, codeception.yml, composer.json, dandelion.json
- Add query expanders
- Add map expanders for adding skus and concrete skus to es index
- Add fields "sku" and "concrete-skus" to es index
- ...
=> Add concrete sku and sku filter to catalog search

Makefile, Makefile.d/composer.sh, Makefile.d/packagist.sh
- Print composer replace section by make or shell
- Add bundles to packagist
=> Add some monorepo helper 🦾

bundles/shipment-table-rate/composer.json, bundles/shipment-table-rate/src/FondOfOryx/Shared/ShipmentTableRate/ShipmentTableRateConstants.php, bundles/shipment-table-rate/src/FondOfOryx/Shared/ShipmentTableRate/Transfer/shipment_table_rate.transfer.xml, bundles/shipment-table-rate/src/FondOfOryx/Zed/ShipmentTableRate/Business/Model/PriceCalculator.php, bundles/shipment-table-rate/src/FondOfOryx/Zed/ShipmentTableRate/Business/Model/VariableExtractor.php, bundles/shipment-table-rate/src/FondOfOryx/Zed/ShipmentTableRate/Business/Model/VariableExtractorInterface.php, bundles/shipment-table-rate/src/FondOfOryx/Zed/ShipmentTableRate/Business/ShipmentTableRateBusinessFactory.php, bundles/shipment-table-rate/src/FondOfOryx/Zed/ShipmentTableRate/Dependency/Service/ShipmentTableRateToUtilMathFormulaServiceBridge.php, bundles/shipment-table-rate/src/FondOfOryx/Zed/ShipmentTableRate/Dependency/Service/ShipmentTableRateToUtilMathFormulaServiceInterface.php, bundles/shipment-table-rate/src/FondOfOryx/Zed/ShipmentTableRate/Persistence/Propel/Schema/foo_shipment_table_rate.schema.xml, bundles/shipment-table-rate/src/FondOfOryx/Zed/ShipmentTableRate/Persistence/ShipmentTableRateRepository.php, bundles/shipment-table-rate/src/FondOfOryx/Zed/ShipmentTableRate/ShipmentTableRateDependencyProvider.php, bundles/shipment-table-rate/tests/FondOfOryx/Zed/ShipmentTableRate/Business/Model/PriceCalculatorTest.php, bundles/shipment-table-rate/tests/FondOfOryx/Zed/ShipmentTableRate/Business/Model/VariableExtractorTest.php, bundles/shipment-table-rate/tests/FondOfOryx/Zed/ShipmentTableRate/Business/ShipmentTableRateBusinessFactoryTest.php, bundles/shipment-table-rate/tests/FondOfOryx/Zed/ShipmentTableRate/Dependency/Service/ShipmentTableRateToUtilMathFormulaServiceBridgeTest.php, bundles/shipment-table-rate/tests/FondOfOryx/Zed/ShipmentTableRate/ShipmentTableRateDependencyProviderTest.php
- Use min_price_to_pay and max_price_to_pay for receiving correct table rate entry
- NULL value for max_price_to_pay equal infinity
- Evaluate shipping price by formula (saved in db)
- Values for formula variables come from QuoteTransfer
- ...
=> Use formula to calculate shipping price 🤑

bundles/util-math-formula/composer.json, composer.json
- util-math-formula instead of util-math-forumla
- add util-math-formula to replace section in main composer.json
- ...
=> Remove typo from package name

bundles/product-locale-restriction/LICENSE, bundles/product-locale-restriction/codeception.yml, bundles/product-locale-restriction/composer.json, bundles/product-locale-restriction/src/FondOfOryx/Shared/ProductLocaleRestriction/Transfer/product_locale_restriction.transfer.xml, bundles/product-locale-restriction/src/FondOfOryx/Zed/ProductLocaleRestriction/Business/Model/ProductAbstractLocaleRestrictionsPersisterInterface.php, bundles/product-locale-restriction/src/FondOfOryx/Zed/ProductLocaleRestriction/Business/ProductLocaleRestrictionFacadeInterface.php, bundles/product-locale-restriction/src/FondOfOryx/Zed/ProductLocaleRestriction/Persistence/ProductLocaleRestrictionEntityManagerInterface.php, bundles/product-locale-restriction/src/FondOfOryx/Zed/ProductLocaleRestriction/Persistence/ProductLocaleRestrictionRepositoryInterface.php, bundles/product-locale-restriction/src/FondOfOryx/Zed/ProductLocaleRestriction/Persistence/Propel/Mapper/ProductAbstractLocaleRestrictionMapperInterface.php, bundles/product-locale-restriction/src/FondOfOryx/Zed/ProductLocaleRestriction/Persistence/Propel/Schema/foo_product_locale_restriction.schema.xml, bundles/product-locale-restriction/tests/_bootstrap.php, bundles/product-locale-restriction/tests/_output/.gitignore, codeception.yml, composer.json, dandelion.json
- add initialize stuff (dandelion entry, composer.json, ...)
- add contracts
=> Initialize product locale restriction module 🇪🇺

bundles/one-time-password-email-connector/LICENSE, bundles/one-time-password-email-connector/codeception.yml, bundles/one-time-password-email-connector/composer.json, bundles/one-time-password-email-connector/src/FondOfOryx/Shared/OneTimePasswordEmailConnector/Transfer/one_time_password_email_connector.transfer.xml, bundles/one-time-password-email-connector/src/FondOfOryx/Zed/OneTimePasswordEmailConnector/Business/Dependency/Facade/OneTimePasswordEmailConnectorToMailBridge.php, bundles/one-time-password-email-connector/src/FondOfOryx/Zed/OneTimePasswordEmailConnector/Business/Dependency/Facade/OneTimePasswordEmailConnectorToMailInterface.php, bundles/one-time-password-email-connector/src/FondOfOryx/Zed/OneTimePasswordEmailConnector/Business/OneTimePasswordEmailConnector.php, bundles/one-time-password-email-connector/src/FondOfOryx/Zed/OneTimePasswordEmailConnector/Business/OneTimePasswordEmailConnectorBusinessFactory.php, bundles/one-time-password-email-connector/src/FondOfOryx/Zed/OneTimePasswordEmailConnector/Business/OneTimePasswordEmailConnectorFacade.php, bundles/one-time-password-email-connector/src/FondOfOryx/Zed/OneTimePasswordEmailConnector/Business/OneTimePasswordEmailConnectorFacadeInterface.php, bundles/one-time-password-email-connector/src/FondOfOryx/Zed/OneTimePasswordEmailConnector/Business/OneTimePasswordEmailConnectorInterface.php, bundles/one-time-password-email-connector/src/FondOfOryx/Zed/OneTimePasswordEmailConnector/Communication/Plugin/Mail/OneTimePasswordEmailConnectorMailTypePlugin.php, bundles/one-time-password-email-connector/src/FondOfOryx/Zed/OneTimePasswordEmailConnector/OneTimePasswordEmailConnectorDependencyProvider.php, bundles/one-time-password-email-connector/src/FondOfOryx/Zed/OneTimePasswordEmailConnector/Presentation/Mail/one_time_password_email_connector.html.twig, bundles/one-time-password-email-connector/src/FondOfOryx/Zed/OneTimePasswordEmailConnector/Presentation/Mail/one_time_password_email_connector.text.twig, bundles/one-time-password-email-connector/tests/_bootstrap.php, bundles/one-time-password-email-connector/tests/_output/.gitignore, bundles/one-time-password/src/FondOfOryx/Shared/OneTimePassword/Transfer/one_time_password.transfer.xml, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/Generator/OneTimePasswordGenerator.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/OneTimePasswordBusinessFactory.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/Sender/OneTimePasswordSender.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Dependency/Facade/OneTimePasswordToOneTimePasswordEmailConnectorFacadeBridge.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Dependency/Facade/OneTimePasswordToOneTimePasswordEmailConnectorFacadeInterface.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/OneTimePasswordDependencyProvider.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Persistence/OneTimePasswordPersistenceFactory.php, composer.json
Add one-time-password-email-connector
=> Add one-time-password-email-connector

bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/OneTimePasswordBusinessFactory.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/OneTimePasswordFacade.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/OneTimePasswordFacadeInterface.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/Resetter/OneTimePasswordResetter.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/Resetter/OneTimePasswordResetterInterface.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Communication/Plugin/ResetOneTimePasswordPostAuthPlugin.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Dependency/QueryContainer/OneTimePasswordToCustomerQueryContainerBridge.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Dependency/QueryContainer/OneTimePasswordToCustomerQueryContainerInterface.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Persistence/OneTimePasswordEntityManager.php, bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Persistence/OneTimePasswordEntityManagerInterface.php
Add ResetOneTimePasswordPostAuthPlugin
=> Add ResetOneTimePasswordPostAuthPlugin

dandelion.json
Add one-time-password packages to dandelion.json
=> Add one-time-password packages to dandelion.json

bundles/erp-order-page-search-rest-api/src/FondOfOryx/Glue/ErpOrderPageSearchRestApi/Model/Mapper/ErpOrderMapper.php, bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/Plugin/SearchExtension/ErpOrderPageSearchOwnParamFilterQueryExpanderPlugin.php
- use terms instead of filter for field reference (erp order page search bundle)
- ...
=> Use terms instead of filter

bundles/jellyfish-availability-alert/composer.json, bundles/jellyfish-availability-alert/src/FondOfOryx/Zed/JellyfishAvailabilityAlert/Business/Api/Adapter/AvailabilityAlertAdapter.php, bundles/jellyfish-availability-alert/src/FondOfOryx/Zed/JellyfishAvailabilityAlert/Business/Api/Adapter/AvailabilityAlertAdapterInterface.php, bundles/jellyfish-availability-alert/src/FondOfOryx/Zed/JellyfishAvailabilityAlert/Business/Dependency/Service/JellyfishAvailabilityAlertToUtilEncodingServiceInterface.php, composer.json
removed usage of jellyfish core (implement adapter instead of abstract adapter)
=> - remove usage of jellyfish core

bundles/product-country-restriction/src/FondOfOryx/Zed/ProductCountryRestriction/Persistence/Propel/Mapper/ProductAbstractCountryRestrictionMapper.php
- use setFkCountry instead of setFkProductAbstract
=> Remove typo in module "product-country-restriction"

bundles/availability-alert-cross-engage/src/FondOfOryx/Shared/AvailabilityAlertCrossEngage/Transfer/availability_alert_cross_engage.transfer.xml, bundles/availability-alert-cross-engage/src/FondOfOryx/Zed/AvailabilityAlertCrossEngage/Business/AvailabilityAlertCrossEngageFacade.php, bundles/availability-alert-cross-engage/src/FondOfOryx/Zed/AvailabilityAlertCrossEngage/Business/AvailabilityAlertCrossEngageFacadeInterface.php, bundles/availability-alert-cross-engage/src/FondOfOryx/Zed/AvailabilityAlertCrossEngage/Communication/Plugin/Notification/CrossEngageNotificationPlugin.php, bundles/availability-alert-cross-engage/src/FondOfOryx/Zed/AvailabilityAlertCrossEngage/Persistence/Propel/Schema/foo_availability_alert.schema.xml, bundles/jellyfish-availability-alert/src/FondOfOryx/Zed/JellyfishAvailabilityAlert/Business/Api/Adapter/AvailabilityAlertAdapter.php
- use request instead of post for guzzle client
- implemented cross engage notification plugin
=> XNG Notification Plugin

bundles/erp-order-page-search-rest-api/src/FondOfOryx/Glue/ErpOrderPageSearchRestApi/Model/Mapper/ErpOrderMapper.php, bundles/erp-order-page-search-rest-api/src/FondOfOryx/Shared/ErpOrderPageSearchRestApi/Transfer/erp_order_page_search_rest_api.transfer.xml, bundles/erp-order-page-search-rest-api/tests/FondOfOryx/Glue/ErpOrderPageSearchRestApi/Model/Mapper/ErpOrderMapperTest.php, bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/Plugin/SearchExtension/ErpOrderPageSearchOwnParamFilterQueryExpanderPlugin.php, bundles/erp-order-page-search/src/FondOfOryx/Zed/ErpOrderPageSearch/Business/Publisher/ErpOrderPageSearchPublisher.php, bundles/erp-order-page-search/tests/FondOfOryx/Client/ErpOrderPageSearch/Plugin/SearchExtension/ErpOrderPageSearchOwnParamFilterQueryExpanderPluginTest.php
- add RestCompanyBusinessUnitTransfer, RestErpOrderTransfer, RestErpOrderAddressTransfer Objects
- fix CompanyBusinessUnitId Filter (in case of "wrong" value, was always CompanyBusinessUnitId From the customer used)
=> expand & cleanup glue response values

bundles/splittable-totals-extension/LICENSE, bundles/splittable-totals-extension/codeception.yml, bundles/splittable-totals-extension/composer.json, bundles/splittable-totals-extension/src/FondOfOryx/Shared/SplittableTotalsExtension/Transfer/splittable_totals_extension.transfer.xml, bundles/splittable-totals-extension/src/FondOfOryx/Zed/SplittableTotalsExtension/Dependency/Plugin/QuoteExpanderPluginInterface.php, bundles/splittable-totals-extension/tests/_bootstrap.php, codeception.yml, composer.json
- provides plugin contracts that will be used by splittable totals
=> Add splittable totals extension module

bundles/splittable-totals/LICENSE, bundles/splittable-totals/codeception.yml, bundles/splittable-totals/composer.json, bundles/splittable-totals/src/FondOfOryx/Shared/SplittableTotals/SplittableTotalsConstants.php, bundles/splittable-totals/src/FondOfOryx/Shared/SplittableTotals/Transfer/splittable_totals.transfer.xml, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Business/Reader/QuoteReaderInterface.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Business/Reader/SplittableTotalsReaderInterface.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Business/SplittableTotalsFacadeInterface.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Business/Splitter/QuoteSplitterInterface.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Dependency/Facade/SplittableTotalsToCalculationFacadeInterface.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Dependency/Facade/SplittableTotalsToQuoteFacadeInterface.php, bundles/splittable-totals/tests/_bootstrap.php, codeception.yml, composer.json
- add initialize stuff (composer.json, codeception.yml, ...)
- add contracts
=> Initialize splittable totals module 🔪

bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Business/Reader/QuoteReader.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Business/Reader/SplittableTotalsReader.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Business/SplittableTotalsBusinessFactory.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Business/SplittableTotalsFacade.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Business/Splitter/QuoteSplitter.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Dependency/Facade/SplittableTotalsToCalculationFacadeBridge.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/Dependency/Facade/SplittableTotalsToQuoteFacadeBridge.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/SplittableTotalsConfig.php, bundles/splittable-totals/src/FondOfOryx/Zed/SplittableTotals/SplittableTotalsDependencyProvider.php, bundles/splittable-totals/tests/FondOfOryx/Zed/SplittableTotals/Business/Reader/QuoteReaderTest.php, bundles/splittable-totals/tests/FondOfOryx/Zed/SplittableTotals/Business/Reader/SplittableTotalsReaderTest.php, bundles/splittable-totals/tests/FondOfOryx/Zed/SplittableTotals/Business/SplittableTotalsBusinessFactoryTest.php, bundles/splittable-totals/tests/FondOfOryx/Zed/SplittableTotals/Business/SplittableTotalsFacadeTest.php, bundles/splittable-totals/tests/FondOfOryx/Zed/SplittableTotals/Business/Splitter/QuoteSplitterTest.php, bundles/splittable-totals/tests/FondOfOryx/Zed/SplittableTotals/Dependency/Facade/SplittableTotalsToCalculationFacadeBridgeTest.php, bundles/splittable-totals/tests/FondOfOryx/Zed/SplittableTotals/Dependency/Facade/SplittableTotalsToQuoteFacadeBridgeTest.php, bundles/splittable-totals/tests/FondOfOryx/Zed/SplittableTotals/SplittableTotalsConfigTest.php, bundles/splittable-totals/tests/FondOfOryx/Zed/SplittableTotals/SplittableTotalsDependencyProviderTest.php
- expand original quote by plugins
- split quote by configurable split item attribute
- recalculates splitted quotes
- retrieves totals per splitted quote
- ...
=> Implement contracts for splittable totals module 🔪

bundles/splittable-totals-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Business/Expander/QuoteExpander.php, bundles/splittable-totals-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Business/Mapper/AddressMapper.php, bundles/splittable-totals-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Business/Reader/CompanyUnitAddressReader.php, bundles/splittable-totals-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Business/SplittableTotalsCompanyUnitAddressConnectorBusinessFactory.php, bundles/splittable-totals-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Business/SplittableTotalsCompanyUnitAddressConnectorFacade.php, bundles/splittable-totals-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Communication/Plugin/SplittableTotalsExtension/CompanyUnitAddressQuoteExpanderPlugin.php, bundles/splittable-totals-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Dependency/Facade/SplittableTotalsCompanyUnitAddressConnectorToCompanyUnitAddressFacadeBridge.php, bundles/splittable-totals-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Persistence/SplittableTotalsCompanyUnitAddressConnectorPersistenceFactory.php, bundles/splittable-totals-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Persistence/SplittableTotalsCompanyUnitAddressConnectorRepository.php, bundles/splittable-totals-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/SplittableTotalsCompanyUnitAddressConnectorDependencyProvider.php, bundles/splittable-totals-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Business/Expander/QuoteExpanderTest.php, bundles/splittable-totals-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Business/Mapper/AddressMapperTest.php, bundles/splittable-totals-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Business/Reader/CompanyUnitAddressReaderTest.php, bundles/splittable-totals-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Business/SplittableTotalsCompanyUnitAddressConnectorBusinessFactoryTest.php, bundles/splittable-totals-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Business/SplittableTotalsCompanyUnitAddressConnectorFacadeTest.php, bundles/splittable-totals-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Communication/Plugin/SplittableTotalsExtension/CompanyUnitAddressQuoteExpanderPluginTest.php, bundles/splittable-totals-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/Dependency/Facade/SplittableTotalsCompanyUnitAddressConnectorToCompanyUnitAddressFacadeBridgeTest.php, bundles/splittable-totals-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsCompanyUnitAddressConnector/SplittableTotalsCompanyUnitAddressConnectorDependencyProviderTest.php
- expands quote with company unit addresses (billing / shipping)
- add quote expander plugin
- ...
=> Implement contracts for splittable totals company unit address connector module 📇

bundles/splittable-totals-rest-api-company-unit-address-connector/composer.json, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Shared/SplittableTotalsRestApiCompanyUnitAddressConnector/Transfer/splittable_totals_rest_api_company_unit_address_connector.transfer.xml, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Business/Expander/QuoteExpander.php, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Business/Expander/QuoteExpanderInterface.php, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Business/Reader/CompanyUnitAddressReader.php, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Business/Reader/CompanyUnitAddressReaderInterface.php, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Business/SplittableTotalsRestApiCompanyUnitAddressConnectorFacade.php, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Business/SplittableTotalsRestApiCompanyUnitAddressConnectorFacadeInterface.php, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Communication/Plugin/SplittableTotalsRestApiExtension/CompanyUnitAddressQuoteExpanderPlugin.php, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Dependency/Facade/SplittableTotalsRestApiCompanyUnitAddressConnectorToCompanyUnitAddressFacadeBridge.php, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Dependency/Facade/SplittableTotalsRestApiCompanyUnitAddressConnectorToCompanyUnitAddressFacadeInterface.php, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Persistence/Propel/Schema/spy_company_unit_address.schema.xml, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Persistence/SplittableTotalsRestApiCompanyUnitAddressConnectorRepository.php, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Persistence/SplittableTotalsRestApiCompanyUnitAddressConnectorRepositoryInterface.php, bundles/splittable-totals-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Business/Expander/QuoteExpanderTest.php, bundles/splittable-totals-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Business/Reader/CompanyUnitAddressReaderTest.php, bundles/splittable-totals-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Business/SplittableTotalsRestApiCompanyUnitAddressConnectorFacadeTest.php, bundles/splittable-totals-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Communication/Plugin/SplittableTotalsRestApiExtension/CompanyUnitAddressQuoteExpanderPluginTest.php, bundles/splittable-totals-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Dependency/Facade/SplittableTotalsRestApiCompanyUnitAddressConnectorToCompanyUnitAddressFacadeBridgeTest.php, bundles/splittable-totals-rest-api-extension/src/FondOfOryx/Shared/SplittableTotalsRestApiExtension/Transfer/splittable_totals_rest_api_extension.transfer.xml, bundles/splittable-totals-rest-api-extension/src/FondOfOryx/Zed/SplittableTotalsRestApiExtension/Dependency/Plugin/QuoteExpanderPluginInterface.php, composer.json
- add uuid behavior and uuid field to company unit address entity
- use new request transfer
- ...
=> Move quote expanding to rest api module (splittable total rest api company unit address connector)

bundles/shipment-table-rate-data-import/src/FondOfOryx/Zed/ShipmentTableRateDataImport/Business/Model/DataSet/ShipmentTableRateDataSet.php, bundles/shipment-table-rate-data-import/src/FondOfOryx/Zed/ShipmentTableRateDataImport/Business/Model/ShipmentTableRateWriterStep.php
- Empty field max_price_to_pay will be null
=> Set correct database value for empty csv column

bundles/return-labels-rest-api/src/FondOfOryx/Glue/ReturnLabelsRestApi/Controller/ReturnLabelsRestApiResourceController.php, bundles/return-labels-rest-api/src/FondOfOryx/Glue/ReturnLabelsRestApi/Plugin/GlueApplicationExtension/ReturnLabelsRestApiResourceRoutePlugin.php, bundles/return-labels-rest-api/src/FondOfOryx/Glue/ReturnLabelsRestApi/Proccesor/ReturnLabelProcessor.php, bundles/return-labels-rest-api/src/FondOfOryx/Glue/ReturnLabelsRestApi/Proccesor/ReturnLabelProcessorInterface.php, bundles/return-labels-rest-api/src/FondOfOryx/Glue/ReturnLabelsRestApi/ReturnLabelsRestApiConfig.php, bundles/return-labels-rest-api/src/FondOfOryx/Glue/ReturnLabelsRestApi/ReturnLabelsRestApiFactory.php, bundles/return-labels-rest-api/src/FondOfOryx/Shared/ReturnLabelsRestApi/Transfer/return_labels_rest_api.transfer.xml, bundles/return-labels-rest-api/tests/FondOfOryx/Glue/ReturnLabelsRestApi/Controller/ReturnLabelsRestApiResourceControllerTest.php, bundles/return-labels-rest-api/tests/FondOfOryx/Glue/ReturnLabelsRestApi/Plugin/GlueApplicationExtension/ReturnLabelsRestApiResourceRoutePluginTest.php, bundles/return-labels-rest-api/tests/FondOfOryx/Glue/ReturnLabelsRestApi/Processor/ReturnLabelProcessorTest.php, bundles/return-labels-rest-api/tests/FondOfOryx/Glue/ReturnLabelsRestApi/ReturnLabelsRestApiFactoryTest.php, bundles/return-labels-rest-api/tests/_bootstrap.php, bundles/return-labels-rest-api/tests/_output/.gitignore
Sorry für den erneuten PR, ich musste da erst mal Ordnung rein bringen. 
Ich stelle für jeden Layer der beiden Bundles einen PR und merge diese erst nach "feature/return-label-bundles" bevor es in den Main-Branch geht.
=> return-labels-rest-api: glue layer + unit tests

bundles/availability-alert-cross-engage/composer.json, bundles/availability-alert-data-import/composer.json, bundles/availability-alert-migrator/composer.json, bundles/availability-alert/composer.json, bundles/erp-order-api/composer.json, bundles/erp-order-page-search-rest-api/composer.json, bundles/erp-order-page-search/composer.json, bundles/erp-order/composer.json, bundles/feed/composer.json, bundles/one-time-password-email-connector/composer.json, bundles/one-time-password-rest-api/composer.json, bundles/one-time-password/composer.json, bundles/product-country-restriction-checkout-connector/composer.json, bundles/product-locale-restriction-cart-connector/composer.json, bundles/product-locale-restriction-search/composer.json, bundles/product-locale-restriction-storage/composer.json, bundles/shipment-table-rate-data-import/composer.json, bundles/shipment-table-rate/composer.json, bundles/splittable-totals-rest-api-company-unit-address-connector/composer.json, bundles/splittable-totals-rest-api/composer.json, dandelion.json
- removed unfinished packages from dandelion.json
=> - changed versions to 1.0.0

bundles/splittable-totals-rest-api/src/FondOfOryx/Client/SplittableTotalsRestApi/Dependency/Client/SplittableTotalsRestApiToZedRequestClientBridge.php, bundles/splittable-totals-rest-api/src/FondOfOryx/Client/SplittableTotalsRestApi/SplittableTotalsRestApiClient.php, bundles/splittable-totals-rest-api/src/FondOfOryx/Client/SplittableTotalsRestApi/SplittableTotalsRestApiDependencyProvider.php, bundles/splittable-totals-rest-api/src/FondOfOryx/Client/SplittableTotalsRestApi/SplittableTotalsRestApiFactory.php, bundles/splittable-totals-rest-api/src/FondOfOryx/Client/SplittableTotalsRestApi/Zed/SplittableTotalsRestApiZedStub.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Client/SplittableTotalsRestApi/Dependency/Client/SplittableTotalsRestApiToZedRequestClientBridgeTest.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Client/SplittableTotalsRestApi/SplittableTotalsRestApiClientTest.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Client/SplittableTotalsRestApi/SplittableTotalsRestApiDependencyProviderTest.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Client/SplittableTotalsRestApi/SplittableTotalsRestApiFactoryTest.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Client/SplittableTotalsRestApi/Zed/SplittableTotalsRestApiZedStubTest.php
- allow to get splittable totals over glue and yves
- ...
=> Implement client contracts for splittable totals rest api module 🧾

bundles/splittable-totals-rest-api/src/FondOfOryx/Glue/SplittableTotalsRestApi/Controller/SplittableTotalsResourceController.php, bundles/splittable-totals-rest-api/src/FondOfOryx/Glue/SplittableTotalsRestApi/Plugin/GlueApplicationExtension/SplittableTotalsRestApiResourceRoutePlugin.php, bundles/splittable-totals-rest-api/src/FondOfOryx/Glue/SplittableTotalsRestApi/Processor/Builder/RestResponseBuilder.php, bundles/splittable-totals-rest-api/src/FondOfOryx/Glue/SplittableTotalsRestApi/Processor/Expander/RestSplittableTotalsRequestExpander.php, bundles/splittable-totals-rest-api/src/FondOfOryx/Glue/SplittableTotalsRestApi/Processor/Mapper/RestSplittableTotalsMapper.php, bundles/splittable-totals-rest-api/src/FondOfOryx/Glue/SplittableTotalsRestApi/Processor/Mapper/RestSplittableTotalsRequestMapper.php, bundles/splittable-totals-rest-api/src/FondOfOryx/Glue/SplittableTotalsRestApi/Processor/Reader/RestSplittableTotalsReader.php, bundles/splittable-totals-rest-api/src/FondOfOryx/Glue/SplittableTotalsRestApi/SplittableTotalsRestApiConfig.php, bundles/splittable-totals-rest-api/src/FondOfOryx/Glue/SplittableTotalsRestApi/SplittableTotalsRestApiFactory.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Glue/SplittableTotalsRestApi/Controller/SplittableTotalsResourceControllerTest.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Glue/SplittableTotalsRestApi/Plugin/GlueApplicationExtension/SplittableTotalsRestApiResourceRoutePluginTest.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Glue/SplittableTotalsRestApi/Processor/Builder/RestResponseBuilderTest.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Glue/SplittableTotalsRestApi/Processor/Expander/RestSplittableTotalsRequestExpanderTest.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Glue/SplittableTotalsRestApi/Processor/Mapper/RestSplittableTotalsMapperTest.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Glue/SplittableTotalsRestApi/Processor/Mapper/RestSplittableTotalsRequestMapperTest.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Glue/SplittableTotalsRestApi/Processor/Reader/RestSplittableTotalsReaderTest.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Glue/SplittableTotalsRestApi/SplittableTotalsRestApiConfigTest.php, bundles/splittable-totals-rest-api/tests/FondOfOryx/Glue/SplittableTotalsRestApi/SplittableTotalsRestApiFactoryTest.php
- add glue endpoint for getting splittable totals (per resource route plugin)
- ...
=> Implement glue contracts for splittable totals rest api module 🧾

bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Business/Expander/QuoteExpander.php, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Business/Mapper/AddressMapper.php, bundles/splittable-totals-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Persistence/SplittableTotalsRestApiCompanyUnitAddressConnectorRepository.php, bundles/splittable-totals-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableTotalsRestApiCompanyUnitAddressConnector/Business/Expander/QuoteExpanderTest.php, bundles/splittable-totals-rest-api/composer.json, codeception.yml, dandelion.json
- add splittable totals x to dandelion.json
- set missing shipping in quote expander (splittable totals rest api company unit address connector)
- add missing dependencies to bundle composer
- prepare unit tests
- ...
=> Make splittable totals x ready for release

bundles/catalog-sku-filter/src/FondOfOryx/Client/CatalogSkuFilter/Plugin/SearchExtension/ConcreteSkuPatternQueryExpanderPlugin.php, bundles/catalog-sku-filter/src/FondOfOryx/Client/CatalogSkuFilter/Plugin/SearchExtension/SkuPatternQueryExpanderPlugin.php, bundles/catalog-sku-filter/src/FondOfOryx/Shared/CatalogSkuFilter/CatalogSkuFilterConstants.php, bundles/catalog-sku-filter/tests/FondOfOryx/Client/CatalogSkuFilter/Plugin/SearchExtension/ConcreteSkuPatternQueryExpanderPluginTest.php, bundles/catalog-sku-filter/tests/FondOfOryx/Client/CatalogSkuFilter/Plugin/SearchExtension/SkuPatternQueryExpanderPluginTest.php, bundles/erp-order/composer.json, dandelion.json
- allow to search after (concrete) sku with wildcard pattern
- add plugins to expand query by new request parameters (concrete-sku-pattern & sku-pattern)
- use php >=7.3 (lower versions are eol)
- ...
=> Add query expander for (concrete) sku pattern

bundles/payment-epc-qr-code/composer.json, bundles/payment-epc-qr-code/src/FondOfOryx/Service/PaymentEpcQrCode/Dependency/Wrapper/QrCodeWrapper.php, bundles/payment-epc-qr-code/src/FondOfOryx/Service/PaymentEpcQrCode/Dependency/Wrapper/QrCodeWrapperInterface.php, bundles/payment-epc-qr-code/src/FondOfOryx/Service/PaymentEpcQrCode/Model/QrCode.php, bundles/payment-epc-qr-code/src/FondOfOryx/Service/PaymentEpcQrCode/Model/QrCodeInterface.php, bundles/payment-epc-qr-code/src/FondOfOryx/Service/PaymentEpcQrCode/Model/QrCodeWriter.php, bundles/payment-epc-qr-code/src/FondOfOryx/Service/PaymentEpcQrCode/Model/QrCodeWriterInterface.php, bundles/payment-epc-qr-code/src/FondOfOryx/Service/PaymentEpcQrCode/PaymentEpcQrCodeConfig.php, bundles/payment-epc-qr-code/src/FondOfOryx/Service/PaymentEpcQrCode/PaymentEpcQrCodeDependencyProvider.php, bundles/payment-epc-qr-code/src/FondOfOryx/Service/PaymentEpcQrCode/PaymentEpcQrCodeService.php, bundles/payment-epc-qr-code/src/FondOfOryx/Service/PaymentEpcQrCode/PaymentEpcQrCodeServiceFactory.php, bundles/payment-epc-qr-code/src/FondOfOryx/Service/PaymentEpcQrCode/PaymentEpcQrCodeServiceInterface.php, bundles/payment-epc-qr-code/src/FondOfOryx/Shared/PaymentEpcQrCode/PaymentEpcQrCodeConstants.php, bundles/payment-epc-qr-code/src/FondOfOryx/Shared/PaymentEpcQrCode/Transfer/payment_epc_qr_code.transfer.xml, bundles/payment-epc-qr-code/src/FondOfOryx/Zed/PaymentEpcQrCode/Business/Model/Expander/ExpanderInterface.php, bundles/payment-epc-qr-code/src/FondOfOryx/Zed/PaymentEpcQrCode/Business/Model/Expander/PaymentEpcQrCodeExpander.php, bundles/payment-epc-qr-code/src/FondOfOryx/Zed/PaymentEpcQrCode/Business/PaymentEpcQrCodeBusinessFactory.php, bundles/payment-epc-qr-code/src/FondOfOryx/Zed/PaymentEpcQrCode/Business/PaymentEpcQrCodeFacade.php, bundles/payment-epc-qr-code/src/FondOfOryx/Zed/PaymentEpcQrCode/Business/PaymentEpcQrCodeFacadeInterface.php, bundles/payment-epc-qr-code/src/FondOfOryx/Zed/PaymentEpcQrCode/Dependency/Plugin/Oms/PaymentEpcQrCodeExpanderPlugin.php, composer.json
- added epc qr code service
- added plugin skeleton
=> Wrapper / implementation for endroid/qr-code

bundles/splittable-totals-extension/LICENSE, bundles/splittable-totals-extension/codeception.yml, bundles/splittable-totals-extension/composer.json, bundles/splittable-totals-extension/src/FondOfOryx/Shared/SplittableTotalsExtension/Transfer/splittable_totals_extension.transfer.xml, bundles/splittable-totals-extension/src/FondOfOryx/Zed/SplittableTotalsExtension/Dependency/Plugin/SplittedQuoteExpanderPluginInterface.php, bundles/splittable-totals-extension/tests/_bootstrap.php, codeception.yml, composer.json, phpstan.neon
- provide plugin to expand splitted quote
- ...
=> Add splittable totals extension module 🧩

bundles/splittable-totals-shipment-connector/src/FondOfOryx/Zed/SplittableTotalsShipmentConnector/Business/Expander/SplittedQuoteExpander.php, bundles/splittable-totals-shipment-connector/src/FondOfOryx/Zed/SplittableTotalsShipmentConnector/Business/SplittableTotalsShipmentConnectorBusinessFactory.php, bundles/splittable-totals-shipment-connector/src/FondOfOryx/Zed/SplittableTotalsShipmentConnector/Business/SplittableTotalsShipmentConnectorFacade.php, bundles/splittable-totals-shipment-connector/src/FondOfOryx/Zed/SplittableTotalsShipmentConnector/Communication/Plugin/SplittableTotalsExtension/ShipmentSplittedQuoteExpanderPlugin.php, bundles/splittable-totals-shipment-connector/src/FondOfOryx/Zed/SplittableTotalsShipmentConnector/Dependency/Facade/SplittableTotalsShipmentConnectorToShipmentFacadeBridge.php, bundles/splittable-totals-shipment-connector/src/FondOfOryx/Zed/SplittableTotalsShipmentConnector/SplittableTotalsShipmentConnectorDependencyProvider.php, bundles/splittable-totals-shipment-connector/tests/FondOfOryx/Zed/SplittableTotalsShipmentConnector/Business/Expander/SplittedQuoteExpanderTest.php, bundles/splittable-totals-shipment-connector/tests/FondOfOryx/Zed/SplittableTotalsShipmentConnector/Business/SplittableTotalsShipmentConnectorBusinessFactoryTest.php, bundles/splittable-totals-shipment-connector/tests/FondOfOryx/Zed/SplittableTotalsShipmentConnector/Business/SplittableTotalsShipmentConnectorFacadeTest.php, bundles/splittable-totals-shipment-connector/tests/FondOfOryx/Zed/SplittableTotalsShipmentConnector/Communication/Plugin/SplittableTotalsExtension/ShipmentSplittedQuoteExpanderPluginTest.php, bundles/splittable-totals-shipment-connector/tests/FondOfOryx/Zed/SplittableTotalsShipmentConnector/Dependency/Facade/SplittableTotalsShipmentConnectorToShipmentFacadeBridgeTest.php, bundles/splittable-totals-shipment-connector/tests/FondOfOryx/Zed/SplittableTotalsShipmentConnector/SplittableTotalsShipmentConnectorDependencyProviderTest.php
- expand splitted quote with shipment and expense information
- add splitted quote expander plugin
- ...
=> Implement contracts for splittable totals shipment connector module 🧾

bundles/splittable-quote/src/FondOfOryx/Zed/SplittableQuote/Business/SplittableQuoteBusinessFactory.php, bundles/splittable-quote/src/FondOfOryx/Zed/SplittableQuote/Business/SplittableQuoteFacade.php, bundles/splittable-quote/src/FondOfOryx/Zed/SplittableQuote/Business/Splitter/QuoteSplitter.php, bundles/splittable-quote/src/FondOfOryx/Zed/SplittableQuote/Dependency/Facade/SplittableQuoteToCalculationFacadeBridge.php, bundles/splittable-quote/src/FondOfOryx/Zed/SplittableQuote/SplittableQuoteConfig.php, bundles/splittable-quote/src/FondOfOryx/Zed/SplittableQuote/SplittableQuoteDependencyProvider.php, bundles/splittable-quote/tests/FondOfOryx/Zed/SplittableQuote/Business/SplittableQuoteBusinessFactoryTest.php, bundles/splittable-quote/tests/FondOfOryx/Zed/SplittableQuote/Business/SplittableQuoteFacadeTest.php, bundles/splittable-quote/tests/FondOfOryx/Zed/SplittableQuote/Business/Splitter/QuoteSplitterTest.php, bundles/splittable-quote/tests/FondOfOryx/Zed/SplittableQuote/Dependency/Facade/SplittableQuoteToCalculationFacadeBridgeTest.php, bundles/splittable-quote/tests/FondOfOryx/Zed/SplittableQuote/SplittableQuoteConfigTest.php, bundles/splittable-quote/tests/FondOfOryx/Zed/SplittableQuote/SplittableQuoteDependencyProviderTest.php
- split quote by item attribute
- expand splitted quote by plugin
- recalculate every splitted quote
- ...
=> Implement contracts for splittable quote module 🧾

bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/Expander/QuoteExpander.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/Mapper/AddressMapper.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/Reader/CompanyUnitAddressReader.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/SplittableCheckoutRestApiCompanyUnitAddressConnectorBusinessFactory.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/SplittableCheckoutRestApiCompanyUnitAddressConnectorFacade.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Communication/Plugin/SplittableCheckoutRestApiExtension/CompanyUnitAddressQuoteExpanderPlugin.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Dependency/Facade/SplittableCheckoutRestApiCompanyUnitAddressConnectorToCompanyUnitAddressFacadeBridge.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Persistence/SplittableCheckoutRestApiCompanyUnitAddressConnectorPersistenceFactory.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Persistence/SplittableCheckoutRestApiCompanyUnitAddressConnectorRepository.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/SplittableCheckoutRestApiCompanyUnitAddressConnectorDependencyProvider.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/Expander/QuoteExpanderTest.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/Mapper/AddressMapperTest.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/Reader/CompanyUnitAddressReaderTest.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/SplittableCheckoutRestApiCompanyUnitAddressConnectorBusinessFactoryTest.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/SplittableCheckoutRestApiCompanyUnitAddressConnectorFacadeTest.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Communication/Plugin/SplittableCheckoutRestApiExtension/CompanyUnitAddressQuoteExpanderPluginTest.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Dependency/Facade/SplittableCheckoutRestApiCompanyUnitAddressConnectorToCompanyUnitAddressFacadeBridgeTest.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/SplittableCheckoutRestApiCompanyUnitAddressConnectorDependencyProviderTest.php
- expands quote with company unit addresses (billing / shipping)
- add quote expander plugin
- ...
=> Implement contracts for splittable checkout rest api company unit address connector module 🧾

bundles/splittable-checkout-rest-api/LICENSE, bundles/splittable-checkout-rest-api/codeception.yml, bundles/splittable-checkout-rest-api/composer.json, bundles/splittable-checkout-rest-api/src/FondOfOryx/Shared/SplittableCheckoutRestApi/Transfer/splittable_checkout_rest_api.transfer.xml, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Business/Expander/QuoteExpanderInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Business/Processor/PlaceOrderProcessorInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Business/Reader/QuoteReaderInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Business/SplittableCheckoutRestApiFacadeInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Dependency/Facade/SplittableCheckoutRestApiToQuoteFacadeInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Dependency/Facade/SplittableCheckoutRestApiToSplittableCheckoutFacadeInterface.php, bundles/splittable-checkout-rest-api/tests/_bootstrap.php
- add zed contracts
- add initialize stuff (composer.json, codeception.yml, ...)
- ...
=> Initialize splittable checkout rest api module 🧩

bundles/cross-engage/src/FondOfOryx/Service/CrossEngage/CrossEngageConfig.php, bundles/cross-engage/src/FondOfOryx/Service/CrossEngage/Model/Generator/HashGenerator.php, bundles/cross-engage/src/FondOfOryx/Shared/CrossEngage/CrossEngageConstants.php, bundles/cross-engage/tests/FondOfOryx/Service/CrossEngage/Model/Generator/HashGeneratorTest.php, bundles/cross-engage/tests/FondOfOryx/Service/CrossEngage/Model/Resolver/LanguagePrefixResolverTest.php, bundles/cross-engage/tests/FondOfOryx/Service/CrossEngage/Model/Url/CrossEngageUrlBuilderTest.php, bundles/cross-engage/tests/FondOfOryx/Service/CrossEngage/Model/Validator/FormValidatorCollectionTest.php, bundles/cross-engage/tests/FondOfOryx/Service/CrossEngage/Model/Validator/HoneypotValidatorTest.php
=> refactoring

bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Business/Reader/SplittableTotalsReader.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Business/Reader/SplittableTotalsReaderInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Business/SplittableCheckoutRestApiBusinessFactory.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Business/SplittableCheckoutRestApiFacade.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Business/SplittableCheckoutRestApiFacadeInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Communication/Controller/GatewayController.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Dependency/Facade/SplittableCheckoutRestApiToSplittableTotalsFacadeBridge.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/Dependency/Facade/SplittableCheckoutRestApiToSplittableTotalsFacadeInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Zed/SplittableCheckoutRestApi/SplittableCheckoutRestApiDependencyProvider.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Zed/SplittableCheckoutRestApi/Business/Reader/SplittableTotalsReaderTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Zed/SplittableCheckoutRestApi/Business/SplittableCheckoutRestApiBusinessFactoryTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Zed/SplittableCheckoutRestApi/Business/SplittableCheckoutRestApiFacadeTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Zed/SplittableCheckoutRestApi/Communication/Controller/GatewayControllerTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Zed/SplittableCheckoutRestApi/Dependency/Facade/SplittableCheckoutRestApiToSplittableTotalsFacadeBridgeTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Zed/SplittableCheckoutRestApi/SplittableCheckoutRestApiDependencyProviderTest.php
- remove duplicate code
- refactoring
- cleanup
- ...
=> Integrate zed layer of spittable totals rest api in spittable checkout rest api

bundles/splittable-checkout-rest-api/src/FondOfOryx/Client/SplittableCheckoutRestApi/SplittableCheckoutRestApiClient.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Client/SplittableCheckoutRestApi/SplittableCheckoutRestApiClientInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Client/SplittableCheckoutRestApi/Zed/SplittableCheckoutRestApiZedStub.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Client/SplittableCheckoutRestApi/Zed/SplittableCheckoutRestApiZedStubInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Shared/SplittableCheckoutRestApi/Transfer/splittable_checkout_rest_api.transfer.xml, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Client/SplittableCheckoutRestApi/SplittableCheckoutRestApiClientTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Client/SplittableCheckoutRestApi/Zed/SplittableCheckoutRestApiZedStubTest.php
- remove duplicate code
- refactoring
- cleanup
- ...
=> Integrate client layer of spittable totals rest api in spittable checkout rest api

bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/Controller/SplittableTotalsResourceController.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/Plugin/GlueApplicationExtension/SplittableCheckoutResourceRoutePlugin.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/Plugin/GlueApplicationExtension/SplittableTotalsResourceRoutePlugin.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/Processor/Builder/SplittableCheckoutRestResponseBuilder.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/Processor/Builder/SplittableCheckoutRestResponseBuilderInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/Processor/Builder/SplittableTotalsRestResponseBuilder.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/Processor/Builder/SplittableTotalsRestResponseBuilderInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/Processor/Mapper/RestSplittableTotalsMapper.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/Processor/Mapper/RestSplittableTotalsMapperInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/Processor/Reader/SplittableTotalsReader.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/Processor/Reader/SplittableTotalsReaderInterface.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/SplittableCheckoutRestApiConfig.php, bundles/splittable-checkout-rest-api/src/FondOfOryx/Glue/SplittableCheckoutRestApi/SplittableCheckoutRestApiFactory.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Glue/SplittableCheckoutRestApi/Controller/SplittableTotalsResourceControllerTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Glue/SplittableCheckoutRestApi/Plugin/GlueApplicationExtension/SplittableCheckoutResourceRoutePluginTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Glue/SplittableCheckoutRestApi/Plugin/GlueApplicationExtension/SplittableTotalsResourceRoutePluginTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Glue/SplittableCheckoutRestApi/Processor/Builder/SplittableCheckoutRestResponseBuilderTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Glue/SplittableCheckoutRestApi/Processor/Builder/SplittableTotalsRestResponseBuilderTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Glue/SplittableCheckoutRestApi/Processor/Mapper/RestSplittableTotalsMapperTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Glue/SplittableCheckoutRestApi/Processor/Reader/RestSplittableTotalsReaderTest.php, bundles/splittable-checkout-rest-api/tests/FondOfOryx/Glue/SplittableCheckoutRestApi/SplittableCheckoutRestApiFactoryTest.php
- remove duplicate code
- refactoring
- cleanup
- ...
=> Integrate glue layer of spittable totals rest api in spittable checkout rest api

bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Shared/SplittableCheckoutRestApiCompanyUnitAddressConnector/Transfer/splittable_checkout_rest_api_company_unit_address_connector.transfer.xml, bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/Mapper/AddressMapper.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/Mapper/AddressMapperTest.php
- map name1 to first name
- map name2 to last name (if it is not null)
- ...
=> Map required fields in address mapper

bundles/splittable-checkout-rest-api-cart-note-connector/src/FondOfOryx/Shared/SplittableCheckoutRestApiCartNoteConnector/Transfer/splittable_checkout_rest_api_cart_note_connector.transfer.xml, bundles/splittable-checkout-rest-api-order-custom-reference-connector/src/FondOfOryx/Shared/SplittableCheckoutRestApiOrderCustomReferenceConnector/Transfer/splittable_checkout_rest_api_order_customer_reference_connector.transfer.xml
- add CartNote to RestSplittableCheckoutRequestAttributes
- add orderCustomReference to RestSplittableCheckoutRequestAttributes
=> Add missing transfer object properties

bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Shared/SplittableCheckoutRestApiCompanyUnitAddressConnector/Transfer/splittable_checkout_rest_api_company_unit_address_connector.transfer.xml, bundles/splittable-checkout-rest-api-company-unit-address-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/Expander/QuoteExpander.php, bundles/splittable-checkout-rest-api-company-unit-address-connector/tests/FondOfOryx/Zed/SplittableCheckoutRestApiCompanyUnitAddressConnector/Business/Expander/QuoteExpanderTest.php, bundles/splittable-checkout-rest-api-shipment-connector/src/FondOfOryx/Shared/SplittableCheckoutRestApiShipmentConnector/Transfer/splittable_checkout_rest_api_shipment_connector.transfer.xml, bundles/splittable-checkout-rest-api-shipment-connector/src/FondOfOryx/Zed/SplittableCheckoutRestApiShipmentConnector/Business/Expander/QuoteExpander.php, bundles/splittable-checkout-rest-api-shipment-connector/tests/FondOfOryx/Zed/SplittableCheckoutRestApiShipmentConnector/Business/Expander/QuoteExpanderTest.php, bundles/splittable-checkout/tests/FondOfOryx/Zed/SplittableCheckout/Business/Workflow/SplittableCheckoutWorkflowTest.php, bundles/splittable-checkout/tests/FondOfOryx/Zed/SplittableCheckout/Dependency/Facade/SplittableCheckoutToQuoteFacadeBridgeTest.php, bundles/splittable-quote-shipment-connector/src/FondOfOryx/Shared/SplittableQuoteShipmentConnector/Transfer/splittable_quote_shipment_connector.transfer.xml, bundles/splittable-quote-shipment-connector/src/FondOfOryx/Zed/SplittableQuoteShipmentConnector/Business/Expander/SplittedQuoteExpander.php, bundles/splittable-quote-shipment-connector/tests/FondOfOryx/Zed/SplittableQuoteShipmentConnector/Business/Expander/SplittedQuoteExpanderTest.php
- prepare shipment on quote level
- add unit tests...
- cleanup transfer.xml
- ...
=> Add single shipment support in first version

bundles/payment-epc-qr-code/src/FondOfOryx/Zed/PaymentEpcQrCode/Business/Model/Expander/PaymentEpcQrCodeExpander.php, bundles/payment-epc-qr-code/tests/FondOfOryx/Zed/PaymentEpcQrCode/Business/Model/Expander/PaymentEpcQrCodeExpanderTest.php, dandelion.json
get correct price to pay (use getPriceToPay)
=> use getPriceToPay

bundles/jellyfish-buffer/src/FondOfOryx/Zed/JellyfishBuffer/Persistence/JellyfishBufferEntityManager.php, bundles/jellyfish-buffer/src/FondOfOryx/Zed/JellyfishBuffer/Persistence/JellyfishBufferPersistenceFactory.php, bundles/jellyfish-buffer/src/FondOfOryx/Zed/JellyfishBuffer/Persistence/Propel/Schema/jellyfish_buffer.schema.xml, bundles/jellyfish-buffer/tests/FondOfOryx/Zed/JellyfishBuffer/Persistence/JellyfishBufferEntityManagerTest.php, bundles/jellyfish-buffer/tests/FondOfOryx/Zed/JellyfishBuffer/Persistence/JellyfishBufferPersistenceFactoryTest.php
- reduce duplicated order export (use findOrCreate)
=> reduce duplicated order export

bundles/cart-code-type/.gitignore, bundles/cart-code-type/LICENSE, bundles/cart-code-type/codeception.yml, bundles/cart-code-type/composer.json, bundles/cart-code-type/src/FondOfOryx/Zed/CartCodeType/Persistence/Propel/Schema/foo_cart_code_type.schema.xml, bundles/cart-code-type/tests/_bootstrap.php, bundles/cart-code-type/tests/_output/.gitignore, codeception.yml, composer.json, dandelion.json
- add new table which contains cart code types
- ...
=> Add cart code type bundle 🧩

bundles/product-cart-code-type-restriction/src/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Business/Expander/ProductAbstractExpander.php, bundles/product-cart-code-type-restriction/src/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Business/Persister/ProductAbstractCartCodeTypeRestrictionsPersister.php, bundles/product-cart-code-type-restriction/src/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Business/ProductCartCodeTypeRestrictionBusinessFactory.php, bundles/product-cart-code-type-restriction/src/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Business/ProductCartCodeTypeRestrictionFacade.php, bundles/product-cart-code-type-restriction/src/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Communication/Plugin/Product/ProductAbstractCartCodeTypeRestrictionProductAbstractAfterCreatePlugin.php, bundles/product-cart-code-type-restriction/src/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Communication/Plugin/Product/ProductAbstractCartCodeTypeRestrictionProductAbstractAfterUpdatePlugin.php, bundles/product-cart-code-type-restriction/src/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Communication/Plugin/Product/ProductAbstractCartCodeTypeRestrictionProductAbstractReadPlugin.php, bundles/product-cart-code-type-restriction/src/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Persistence/ProductCartCodeTypeRestrictionEntityManager.php, bundles/product-cart-code-type-restriction/src/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Persistence/ProductCartCodeTypeRestrictionPersistenceFactory.php, bundles/product-cart-code-type-restriction/src/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Persistence/ProductCartCodeTypeRestrictionRepository.php, bundles/product-cart-code-type-restriction/src/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Persistence/Propel/Mapper/ProductAbstractCartCodeTypeRestrictionMapper.php, bundles/product-cart-code-type-restriction/tests/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Business/Expander/ProductAbstractExpanderTest.php, bundles/product-cart-code-type-restriction/tests/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Business/Persister/ProductAbstractCartCodeTypeRestrictionsPersisterTest.php, bundles/product-cart-code-type-restriction/tests/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Business/ProductCartCodeTypeRestrictionBusinessFactoryTest.php, bundles/product-cart-code-type-restriction/tests/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Business/ProductCartCodeTypeRestrictionFacadeTest.php, bundles/product-cart-code-type-restriction/tests/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Communication/Plugin/Product/ProductAbstractCartCodeTypeRestrictionProductAbstractAfterCreatePluginTest.php, bundles/product-cart-code-type-restriction/tests/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Communication/Plugin/Product/ProductAbstractCartCodeTypeRestrictionProductAbstractAfterUpdatePluginTest.php, bundles/product-cart-code-type-restriction/tests/FondOfOryx/Zed/ProductCartCodeTypeRestriction/Communication/Plugin/Product/ProductAbstractCartCodeTypeRestrictionProductAbstractReadPluginTest.php
- expand product abstract with blacklisted cart code types (transfer and ids)
- persist blacklisted cart code types after add or update product
- ...
=> Implement contracts for product cart code type restriction bundle
